name: uniplanner
description: Aplicaci칩n m칩vil de organizaci칩n estudiantil
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  table_calendar: ^3.2.0
  intl: ^0.20.2
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.0.4
  dropdown_button2: ^2.3.9
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  rxdart: ^0.28.0
  firebase_storage: ^12.4.5
  connectivity_plus: ^6.1.4

  local_auth_android: ^1.0.34
  local_auth_windows: ^1.0.10

  google_sign_in: ^6.2.1

  local_auth: ^2.1.7
  flutter_local_notifications: ^19.2.1
  android_intent_plus: ^5.3.0
  permission_handler: ^12.0.0+1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  firebase_messaging: ^15.2.6
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/uniplanner-icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.jpg
    - assets/images/back_icon.png
    - assets/images/user_avatar.png
    - assets/images/theme_icon.png
    - assets/images/user_settings_icon.png
    - assets/images/uniplanner.jpeg
    - assets/images/uniplannerlogo.png
    - assets/images/google_logo.png
    - assets/images/splash.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf

localizations:
  arb-dir: lib/l10n # Directorio donde estar치n los archivos .arb
  template-arb-file: app_es.arb # Archivo base de idioma
  output-localization-file: app_localizations.dart # Archivo generado
